---
- hosts: localhost
  gather_facts: false
  collections: [kubernetes.core]
  vars:
    app_name: airport-greeting-app
    # use an unprivileged image that listens on 8080
    image_ref: "nginxinc/nginx-unprivileged:stable-alpine"

  pre_tasks:
    - name: Resolve target namespace with default
      ansible.builtin.set_fact:
        ns: "{{ target_ns | default('demo-dev') }}"

  tasks:
    - name: Airport landing page (env aware)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ app_name }}-web"
            namespace: "{{ ns }}"
          data:
            index.html: |
              <!doctype html>
              <html>
              <head>
                <title>{{ ns | upper }} Airport</title>
                <meta charset="utf-8"/>
                <style>
                  body{font-family:system-ui;margin:0;padding:0;display:flex;align-items:center;justify-content:center;height:100vh;background:#0f172a;color:white}
                  .card{background:#111827;border-radius:16px;box-shadow:0 10px 30px rgba(0,0,0,.4);padding:32px;text-align:center}
                  h1{margin:0 0 8px;font-size:28px}
                  p{margin:0;opacity:.8}
                </style>
              </head>
              <body>
                <div class="card">
                  <h1>✈️ Welcome to {{ ns | upper }} Airport</h1>
                  <p>Deployed by Ansible Automation Platform</p>
                </div>
              </body>
              </html>

    - name: Deployment (non-root, requests set)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ app_name }}"
            namespace: "{{ ns }}"
          spec:
            replicas: 2
            selector:
              matchLabels: { app: "{{ app_name }}" }
            template:
              metadata:
                labels: { app: "{{ app_name }}" }
              spec:
                securityContext:
                  runAsNonRoot: true
                containers:
                  - name: web
                    image: "{{ image_ref }}"
                    ports:
                      - containerPort: 8080
                    resources:
                      requests:
                        cpu: "100m"
                        memory: "128Mi"
                      limits:
                        cpu: "250m"
                        memory: "256Mi"
                    volumeMounts:
                      - name: web
                        mountPath: /usr/share/nginx/html/index.html
                        subPath: index.html
                volumes:
                  - name: web
                    configMap:
                      name: "{{ app_name }}-web"

    - name: Service (target 8080)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ app_name }}"
            namespace: "{{ ns }}"
          spec:
            selector: { app: "{{ app_name }}" }
            ports:
              - name: http
                port: 80
                targetPort: 8080

    - name: Route (OpenShift)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ app_name }}"
            namespace: "{{ ns }}"
          spec:
            to:
              kind: Service
              name: "{{ app_name }}"
